"use strict";this.default_tr=this.default_tr||{};(function(_){var window=this;
try{
_.ma("sy1");

/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
_.Wg=function(){return _.t("Firefox")||_.t("FxiOS")};_.Xg=function(){return(_.t("Chrome")||_.t("CriOS"))&&!_.t("Edge")||_.t("Silk")};_.Yg=function(){return _.t("Safari")&&!(_.Xg()||_.t("Coast")||_.t("Opera")||_.t("Edge")||_.t("Edg/")||_.t("OPR")||_.Wg()||_.t("Silk")||_.t("Android"))};_.Zg=function(){return _.t("Android")&&!(_.Xg()||_.Wg()||_.t("Opera")||_.t("Silk"))};_.$g=_.Wg();_.ah=_.Da()||_.t("iPod");_.bh=_.t("iPad");_.ch=_.Zg();_.dh=_.Xg();_.eh=_.Yg()&&!_.Ea();

_.oa();

}catch(e){_._DumpException(e)}
try{
_.ma("sy0");

var hh,jh,ih,nh,oh,ph,uh,yh;_.gh=function(a){Object.isFrozen(a)||(fh?a[fh]|=1:void 0!==a.g?a.g|=1:Object.defineProperties(a,{g:{value:1,configurable:!0,writable:!0,enumerable:!1}}));return a};hh=function(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object};jh=function(a,b){if(null!=a){if(Array.isArray(a))a=ih(a,b);else if(hh(a)){var c={},d;for(d in a)c[d]=jh(a[d],b);a=c}else a=b(a);return a}};
ih=function(a,b){for(var c=a.slice(),d=0;d<c.length;d++)c[d]=jh(c[d],b);if(b=Array.isArray(a)){var e;fh?e=a[fh]:e=a.g;b=(null==e?0:e)&1}b&&_.gh(c);return c};
nh=function(a){if(a&&"object"==typeof a&&a.toJSON)return a.toJSON();a:switch(typeof a){case "number":a=isFinite(a)?a:String(a);break a;case "object":if(a&&!Array.isArray(a)&&kh&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);_.lh();b=mh[b];for(var c=Array(Math.floor(a.length/3)),d=b[64]||"",e=0,f=0;e<a.length-2;e+=3){var g=a[e],k=a[e+1],l=a[e+2],m=b[g>>2];g=b[(g&3)<<4|k>>4];k=b[(k&15)<<2|l>>6];l=b[l&63];c[f++]=m+g+k+l}m=0;l=d;switch(a.length-e){case 2:m=a[e+1],l=b[(m&15)<<2]||d;case 1:a=
a[e],c[f]=b[a>>2]+b[(a&3)<<4|m>>4]+l+d}a=c.join("")}}return Array.isArray(a)?ih(a,nh):a};oh={};ph={};_.qh=function(a,b){this.g=a===oh&&b||"";this.h=ph};_.qh.prototype.qb=!0;_.qh.prototype.Wa=function(){return this.g};_.rh=function(a){return new _.qh(oh,a)};_.sh=function(a,b){return _.kd(a.U,b)};_.th=function(a){return a instanceof _.qh&&a.constructor===_.qh&&a.h===ph?a.g:"type_error:Const"};uh=/^[\w+/_-]+[=]{0,2}$/;
_.vh=function(a,b){b=(b||_.p).document;return b.querySelector?(a=b.querySelector(a))&&(a=a.nonce||a.getAttribute("nonce"))&&uh.test(a)?a:"":""};_.wh=function(a){return _.vh("script[nonce]",a)};_.xh=function(a){return String(a).replace(/\-([a-z])/g,function(b,c){return c.toUpperCase()})};yh=function(a){return a.replace(RegExp("(^|[\\s]+)([a-z])","g"),function(b,c,d){return c+d.toUpperCase()})};_.zh=function(a){if(a instanceof _.te)return a;var b=new _.te(_.v);_.se(b,2,a);return b};
_.Ah=function(a,b,c,d,e,f,g){var k=new _.rg;_.ug.push(k);b&&k.D("complete",b);k.Vb("ready",k.aa);f&&(k.s=Math.max(0,f));g&&(k.W=g);k.send(a,c,d,e)};
/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var mh;mh={};_.Bh=null;_.Ch=_.C||_.D||!_.eh&&!_.B&&"function"==typeof _.p.atob;_.lh=function(){if(!_.Bh){_.Bh={};for(var a="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),b=["+/=","+/","-_=","-_.","-_"],c=0;5>c;c++){var d=a.concat(b[c].split(""));mh[c]=d;for(var e=0;e<d.length;e++){var f=d[e];void 0===_.Bh[f]&&(_.Bh[f]=e)}}}};
var kh="function"===typeof Uint8Array;
var fh="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;
_.Fh=function(a,b,c){var d=_.Dh;_.Dh=null;a||(a=d);d=this.constructor.Cl;a||(a=d?[d]:[]);this.j=(d?0:-1)-(this.constructor.Al||0);this.g=void 0;this.kb=a;a:{d=this.kb.length;a=d-1;if(d&&(d=this.kb[a],hh(d))){this.l=a-this.j;this.h=d;break a}void 0!==b&&-1<b?(this.l=Math.max(b,a+1-this.j),this.h=void 0):this.l=Number.MAX_VALUE}if(c)for(b=0;b<c.length;b++)if(a=c[b],a<this.l)a+=this.j,(d=this.kb[a])?Array.isArray(d)&&_.gh(d):this.kb[a]=_.Eh;else{d=this.h||(this.h=this.kb[this.l+this.j]={});var e=d[a];
e?Array.isArray(e)&&_.gh(e):d[a]=_.Eh}};_.Eh=Object.freeze(_.gh([]));_.Gh=function(a,b,c){return-1===b?null:b>=a.l?a.h?a.h[b]:void 0:(void 0===c?0:c)&&a.h&&(c=a.h[b],null!=c)?c:a.kb[b+a.j]};_.Hh=function(a,b,c,d){b<a.l&&(void 0===d||!d)?a.kb[b+a.j]=c:(a.h||(a.h=a.kb[a.l+a.j]={}))[b]=c;return a};_.Ih=function(a,b,c){var d;a.g||(a.g={});var e=c?c.kb:c;a.g[b]=c;return _.Hh(a,b,e,void 0===d?!1:d)};_.Fh.prototype.toJSON=function(){return ih(this.kb,nh)};_.Fh.prototype.toString=function(){return this.kb.toString()};
var Kh;_.L=function(a,b,c){if("string"===typeof b)(b=_.Jh(a,b))&&(a.style[b]=c);else for(var d in b){c=a;var e=b[d],f=_.Jh(c,d);f&&(c.style[f]=e)}};Kh={};_.Jh=function(a,b){var c=Kh[b];if(!c){var d=_.xh(b);c=d;void 0===a.style[d]&&(d=(_.D?"Webkit":_.C?"Moz":_.B?"ms":null)+yh(d),void 0!==a.style[d]&&(c=d));Kh[b]=c}return c};_.Lh=_.C?"MozUserSelect":_.D||_.ic?"WebkitUserSelect":null;

_.oa();

}catch(e){_._DumpException(e)}
try{
_.ma("navigationui");

var gw=function(a,b){_.Hh(a,b,void 0,!1);return a},hw=function(a){var b,c=null===(b=_.Ma())||void 0===b?void 0:b.createScriptURL(a);return new _.Na(null!==c&&void 0!==c?c:a,_.Qa)},iw=function(a){var b=_.lb.apply(1,arguments);if(0===b.length)return hw(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return hw(c.join(""))},kw=function(a){var b=0;return function(){var c=window.scrollY;0!==b&&0!==c||"100%"!==a.style.width||"100%"===a.style.height||jw(a);b=c}},
nw=function(a){return function(b){switch(b.data.Ib5Lyf){case "open":a.classList.add("DNkvFf");break;case "closed":a.classList.remove("DNkvFf");break;default:a.classList.remove("DNkvFf")}lw(a,!mw.matches)}},lw=function(a,b){a.classList.contains("DNkvFf")&&b?document.documentElement.style.overflow="hidden":document.documentElement.style.overflow=ow},sw=function(a,b){return function(c){c=c.data.XAAHIb;"cleanup"===c?pw=new Set:pw.add(c);switch(c){case "topbar.exit":jw(a);a.style.transition="top 0.2s ease";
document.body.style.transition="margin-top 0.2s ease";a.style.top=qw;document.body.style.marginTop="0";break;case "bubble.shape":rw(a,b,{top:qw,transition:"top 0.5s ease"});break;case "bubble.entry":a.style.top="56px";break;case "bubble.exit":a.style.top=qw;break;case "topbar.shape":jw(a,{top:qw,transition:"top 0.2s ease"},{marginTop:"0",transition:"margin-top 0.2s ease"});break;case "topbar.entry":a.style.top="0";document.body.style.marginTop="56px";break;case "cleanup":a.style.transition="none",
document.body.style.transition="none"}}},vw=function(a,b){return function(c){c=c.data.rcuQ6b;switch(c.type){case "topbar":c=c.source;c in tw&&(1===tw[c]?delete tw[c]:--tw[c]);c=pw.size;var d=Object.keys(tw).length;0===c&&0===d&&jw(a);break;case "fullscreen":c=c.source;tw[c]=c in tw?tw[c]+1:1;_.L(a,uw);document.body.style.marginTop="56px";break;case "bubble":rw(a,b);break;default:jw(a)}}},jw=function(a,b,c){b=void 0===b?{}:b;c=void 0===c?{}:c;_.L(a,ww(0===window.scrollY?xw:yw,b));_.L(document.body,
ww({marginTop:"56px"},c))},rw=function(a,b,c){c=void 0===c?{}:c;b=b?ww(zw,{left:"16px",right:"auto"}):zw;_.L(a,ww(b,c));document.body.style.marginTop="0"},ww=function(a,b){return 0!==Object.keys(b).length?Object.assign({},a,b):a},Aw=function(a){var b;return null===(b=a.formContent)||void 0===b?void 0:b.locale},Dw=function(a){var b,c=Aw(a);c=(c&&Bw.includes(c)?Aw(a):"en").replaceAll("-","_").toLowerCase();a=(null===(b=a.initializationData)||void 0===b?0:b.useNightlyRelease)?"nightly":"live";return iw(Cw,
a,c)},Fw=function(a,b){if(Ew)return Ew;var c=Dw(a),d=b.document;return Ew=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(e,f){var g=d.createElement("script");_.Xa(g,c);g.onload=function(){b.feedbackV2GlobalObject?e(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+c.toString())};d.body.appendChild(g)})},Jw=function(a,b,c){var d=!0;d=void 0===d?!0:d;var e,f,g,k,l,
m;Gw(new Hw(new Iw(function(n){switch(n.h){case 1:g=Date.now();k=c||_.p;var q=Fw(a,k);n.h=2;return{value:q};case 2:l=n.o;if(!(d||(null===(e=a.initializationData)||void 0===e?0:e.useNightlyRelease)||(null===(f=a.initializationData)||void 0===f?0:f.isLocalServer))){m=l.initializeFeedbackClient(a,g,b);n.h=3;break}q=l.initializeFeedbackClientAsync(a,g,b);n.h=4;return{value:q};case 4:m=n.o;case 3:return m.initiateAloha(),n.return(m)}})))},Nw=function(a){return Gw(new Hw(new Iw(function(b){return b.return(new Promise(function(c){_.Ah("https://www.google.com/tools/feedback/aloha_form_properties?productId="+
a,function(d){var e=d.target;d=null;try{var f=JSON,g=f.stringify;if(e.g){var k=e.g.responseText;0==k.indexOf(")]}'\n")&&(k=k.substring(5));b:{if(_.p.JSON)try{var l=_.p.JSON.parse(k);break b}catch(r){}l=Kw(k)}}else l=void 0;var m=g.call(f,l),n=m?JSON.parse(m):null;_.Dh=n;var q=new Lw(n);_.Dh=null;d=q}catch(r){g=new Lw,l=new Mw,l=gw(l,5),l=gw(l,2),l=gw(l,4),d=_.Ih(g,1,l)}c(d)},"GET","",{},2E3,!0)}))})))},Xw=function(a){return function(b){b=b.data.N7Eqid;var c=String(Number("2147483646")+1),d={},e={locale:"it",
productData:{WEBSITE_TRANSLATION_PROXY_URL:a.sh,WEBSITE_TRANSLATION_SOURCE_URL:a.Zb,SOURCE_LANGUAGE:a.Bh,TARGET_LANGUAGE:a.Fh}};e=Ow(Pw,"help.service.Lazy.create","101820",{apiKey:e.apiKey||e.apiKey,environment:e.Bg||e.environment,helpCenterPath:e.yl||e.helpCenterPath,locale:e.locale||e.locale||"it".replace(/-/g,"_"),nonce:e.nonce||e.nonce,productData:e.productData||e.productData,receiverUri:e.El||e.receiverUri,renderApiUri:e.Fl||e.renderApiUri,theme:e.Il||e.theme,window:e.window||e.window});(new Ww(e)).h((d.allowNonLoggedInFeedback=
!0,d.bucket="ProxyWebsiteTranslation",d.customZIndex=c,d.productVersion=b,d))}},Yw=function(a){return a.some(function(b){return"childList"===b.type&&Array.from(b.addedNodes).some(function(c){return"google-feedback-wizard"===c.id})})},bx=function(a,b){var c=b.sh,d=b.Zb,e=b.Bh,f=b.Fh,g=b.yg,k=b.si,l=b.mj,m=b.dk,n={},q={},r={},z={};b=Object.assign((n.parent=b.Rj,n.pfu=c,n.u=d,n.sl=e,n.tl=f,n.opu=m,n),g?(q.hl=g,q):null,k?(r.lang=k,r):null,l?(z.op="true",z):null);a=Zw(a);a=$w.exec(_.Wa(a).toString());
c=a[3]||"";return _.Nb(a[1]+ax("?",a[2]||"",b)+ax("#",c,void 0))},cx=function(a){a=new URL(a.Wa());return a.protocol+"//"+a.hostname},dx=function(a,b,c,d){return function(e){e.data.rcuQ6b&&a(e);e.data.N7Eqid&&b(e);e.data.XAAHIb&&c(e);e.data.Ib5Lyf&&d(e);e.Xh.send("DONE",void 0,void 0)}},$w=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,ax=function(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?
e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b},Kw=function(a){try{return _.p.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,
"")))try{return eval("("+a+")")}catch(b){}throw Error("I`"+a);},ex=function(a,b){a=_.Gh(a,b);a=null==a?a:!!a;return null==a?!1:a},fx=function(a){return a.raw=a},gx=function(){this.j=!1;this.g=null;this.o=void 0;this.h=1;this.C=0;this.l=null},hx=function(a){if(a.j)throw new TypeError("f");a.j=!0},Iw,lx,jx,kx,Hw,Gw,mx,Zw;gx.prototype.s=function(a){this.o=a};var ix=function(a,b){a.l={xi:b,jj:!0};a.h=a.C};gx.prototype.return=function(a){this.l={return:a};this.h=this.C};
Iw=function(a){this.g=new gx;this.h=a};lx=function(a,b){hx(a.g);var c=a.g.g;if(c)return jx(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return kx(a)};jx=function(a,b,c,d){try{var e=b.call(a.g.g,c);if(!(e instanceof Object))throw new TypeError("e`"+e);if(!e.done)return a.g.j=!1,e;var f=e.value}catch(g){return a.g.g=null,ix(a.g,g),kx(a)}a.g.g=null;d.call(a.g,f);return kx(a)};
kx=function(a){for(;a.g.h;)try{var b=a.h(a.g);if(b)return a.g.j=!1,{value:b.value,done:!1}}catch(c){a.g.o=void 0,ix(a.g,c)}a.g.j=!1;if(a.g.l){b=a.g.l;a.g.l=null;if(b.jj)throw b.xi;return{value:b.return,done:!0}}return{value:void 0,done:!0}};
Hw=function(a){this.next=function(b){hx(a.g);a.g.g?b=jx(a,a.g.g.next,b,a.g.s):(a.g.s(b),b=kx(a));return b};this.throw=function(b){hx(a.g);a.g.g?b=jx(a,a.g.g["throw"],b,a.g.s):(ix(a.g,b),b=kx(a));return b};this.return=function(b){return lx(a,b)};this[Symbol.iterator]=function(){return this}};Gw=function(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})};mx=/%{(\w+)}/g;
Zw=function(a){var b={},c=_.th(a);if(!_.Mb.test(c))throw Error("o`"+c);a=c.replace(mx,function(d,e){if(!Object.prototype.hasOwnProperty.call(b,e))throw Error("p`"+e+"`"+c+"`"+JSON.stringify(b));d=b[e];return d instanceof _.qh?_.th(d):encodeURIComponent(String(d))});return _.Nb(a)};_.Va=function(){};_.Na=function(a){this.g=a};_.u(_.Na,_.Va);_.Na.prototype.toString=function(){return this.g.toString()};
var nx=function(a){this.g=a;a.then((0,_.w)(function(){},this),function(){},this)},ox=function(a,b){a.g.then(function(c){var d=c.startFeedback;if(!d)throw Error("Ga`startFeedback");return d.apply(c,b)})},Ow=function(a,b,c){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];e=px(a,b).then(function(f){return f.apply(null,d)});return new nx(e)},qx={},px=function(a,b){var c=qx[b];if(c)return c;c=(c=_.rb(b))?_.zh(c):(new _.te(function(d,e){var f=_.sh(new _.dd(document),"SCRIPT");
f.async=!0;_.Xa(f,_.Nb(_.th(a)));f.onload=f.onreadystatechange=function(){f.readyState&&"loaded"!=f.readyState&&"complete"!=f.readyState||d()};f.onerror=e;(document.head||document.getElementsByTagName("head")[0]).appendChild(f)})).then(function(){var d=_.rb(b);if(!d)throw Error("Ha`"+b+"`"+a);return d});return qx[b]=c};
var Ww=function(a){this.g=a};Ww.prototype.h=function(a){ox(this.g,arguments)};var Pw=_.rh("https://www.gstatic.com/feedback/js/help/prod/service/lazy.min.js"),rx=px(Pw,"help.service.Lazy.create");_.xe(rx,null,function(){},void 0);
var sx=parseInt("56px",10)+parseInt("1px",10)+"px",qw="-"+(parseInt("56px",10)+parseInt("5px",10)+"px"),mw=window.matchMedia("(min-width: 1280px)"),ow=document.documentElement.style.overflow||"auto",tx={border:"none",borderRadius:"0",boxShadow:"none",height:"auto",left:"auto",right:"auto",position:"fixed",top:"auto",transition:"none",width:"auto",zIndex:"2147483646"},xw=ww(tx,{height:sx,left:"0",top:"0",width:"100%"}),yw=ww(xw,{height:"56px",boxShadow:"0px 1px 2px rgba(60, 64, 67, 0.3), 0px 2px 6px 2px rgba(60, 64, 67, 0.15)"}),
uw=ww(xw,{height:"100%"}),zw=ww(tx,{borderRadius:"50%",boxShadow:"0px 4px 8px 3px rgba(60, 64, 67, 0.15), 0px 1px 3px rgba(60, 64, 67, 0.3)",height:"56px",left:"auto",right:"16px",top:"56px",width:"56px"}),pw=new Set,tw={};
var Mw=function(a){_.Fh.call(this,a)};_.u(Mw,_.Fh);_.h=Mw.prototype;_.h.getEnableSsEngine=function(){return ex(this,2)};_.h.getEnableAwr=function(){return ex(this,3)};_.h.getEnableHelpSuggestions=function(){return ex(this,4)};_.h.getAlohaAutoGaRollout=function(){return ex(this,5)};_.h.getEnableConfigurator=function(){return ex(this,6)};
var Lw=function(a){_.Fh.call(this,a)};_.u(Lw,_.Fh);
var Bw="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");
var Cw=fx(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);
var Ew;
var ux="5147080 127 92912 69228 69390 145".split(" "),vx=function(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||_.p,e=d.document,f=a.nonce||_.wh(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){var g=_.rb("document.location.href",d);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var k=JSON.stringify(b);(g=1200>=k.length)&&(a.psdJson=k)}g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.serverUri||"//www.google.com/tools/feedback";
if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);else{d=c+"/load.js?";for(var l in a)b=a[l],null==b||_.ya(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=_.sh(_.F(e),"SCRIPT");f&&a.setAttribute("nonce",f);_.Xa(a,_.Nb(d));e.body.appendChild(a)}};
_.Ab("userfeedback.api.startFeedback",function(a,b,c){try{"submit"===a.flow?vx(a,b,c):"help"==a.flow?vx(a,b,c):ux.includes(a.productId)?Nw(a.productId).then(function(d){d.g||(d.g={});var e=d.g[1];if(e)d=e;else{var f=_.Gh(d,1,!1);null==f?d=e:(e=new Mw(f),d=d.g[1]=e)}if(null!=d&&!0===d.getAlohaAutoGaRollout()){e=c||_.p;f="DEV"===a.serverEnvironment;var g=c||_.p;g=a.nonce||_.wh(g);f={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},
formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,Jl:void 0,defaultFormInputValues:void 0,defaultFormInputValuesString:void 0,abuseLink:a.abuseLink},initializationData:{isLocalServer:f,nonce:g,useNightlyRelease:f,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0},extraData:{productVersion:a.productVersion,
authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,enableAnonymousFeedback:a.enableAnonymousFeedback}};b&&(g=new Map(Object.entries(b)),f.extraData.productSpecificData=g);Jw(f,d,e)}else vx(a,b,c)},function(){return vx(a,b,c)}):vx(a,b,c)}catch(d){vx(a,b,c)}});
var wx={autopush:_.rh("https://translate-autopush.sandbox.google.com/websitetranslationui"),staging:_.rh("https://translate1.sandbox.google.com/websitetranslationui"),prod:_.rh("https://translate.google.com/websitetranslationui")},xx=wx.prod;
var yx=Promise;
var zx=function(a){this.g=a};zx.prototype.send=function(a,b,c){this.g.then(function(d){d.send(a,b,c)})};
var Ax=function(a,b){this.data=a;this.Xh=b};
var Bx=function(a){this.g=a};Bx.prototype.send=function(a,b,c){c=void 0===c?[]:c;var d=new MessageChannel;Cx(d.port1,b);this.g.postMessage(a,[d.port2].concat(c))};var Dx=function(a,b){Cx(a,b);return new Bx(a)},Cx=function(a,b){b&&(a.onmessage=function(c){b(new Ax(c.data,Dx(c.ports[0],void 0)))})};
var Gx=function(a){var b=a.fc,c=void 0===a.Ld?"ZNWN1d":a.Ld,d=void 0===a.onMessage?void 0:a.onMessage,e=void 0===a.je?void 0:a.je;return Ex({destination:a.destination,ef:function(){return b.contentWindow},Mj:Fx(a.origin),Ld:c,onMessage:d,je:e})},Ex=function(a){var b=a.destination,c=a.ef,d=a.Mj,e=void 0===a.gk?void 0:a.gk,f=a.Ld,g=void 0===a.onMessage?void 0:a.onMessage,k=void 0===a.je?void 0:a.je,l=Object.create(null);d.forEach(function(m){l[m]=!0});return new zx(new yx(function(m,n){var q=function(r){if(r.source===
c())if(!0!==l[r.origin]){b.removeEventListener("message",q,!1);var z=d.join(", ");n(Error("Ia`"+(1===d.length?z:"one of ["+z+"]")+"`"+r.origin))}else(r.data.n||r.data)===f&&(b.removeEventListener("message",q,!1),e&&r.data.t!==e?n(Error("Ja`"+e+"`"+r.data.t)):(m(Dx(r.ports[0],g)),k&&k(r)))};b.addEventListener("message",q,!1)}))},Fx=function(a){a="string"===typeof a?[a]:a;var b=Object.create(null);a.forEach(function(c){if("null"===c)throw Error("Ka");b[c]=!0});return a};
var Hx=document.currentScript.getAttribute("data-environment"),Ix=document.currentScript.getAttribute("data-proxy-url"),Jx=document.currentScript.getAttribute("data-proxy-full-url"),Kx=document.currentScript.getAttribute("data-source-url"),Lx=document.currentScript.getAttribute("data-source-language"),Mx=document.currentScript.getAttribute("data-target-language"),Nx=document.currentScript.getAttribute("data-display-language"),Ox=document.currentScript.getAttribute("data-detected-source-language"),
Px=document.currentScript.getAttribute("data-is-source-untranslated"),Qx=document.currentScript.getAttribute("data-source-untranslated-url");
(function(a){var b=_.kd(document,"IFRAME"),c=wx[a.Bg.toLowerCase()]||xx,d=bx(c,a),e=_.Jb.test(a.yg),f=kw(b),g=vw(b,e);e=sw(b,e);var k=nw(b);a=Xw(a);jw(b);b.title="Google Translate navigation";b.allowTransparency="true";b.frameBorder="0";b.id="gt-nvframe";b.setAttribute("role","navigation");b.setAttribute("aria-label","Google Translate navigation");b.src=d instanceof _.Va?_.Oa(d).toString():_.Wa(d).toString();document.body.prepend(b);var l=Gx({Ld:"zREjac",destination:window,fc:b,origin:cx(c),onMessage:dx(g,
a,e,k)});c={};l.send((c.woLtV="inprogress",c));_.H(window,"load",function(){var m={};l.send((m.woLtV="complete",m))});_.H(window,"scroll",f);mw.addEventListener("change",function(m){return lw(b,!m.matches)})})({Bg:Hx,Rj:Ix,sh:Jx,Zb:Kx,Bh:Lx,Fh:Mx,yg:Nx,si:Ox,mj:"true"==Px.toLowerCase(),dk:Qx});
(function(a){if(void 0===a?0:a){var b=_.kd(document,"DIV");b.id="OQ2Y6";b.style.height="100%";b.style.width="100%";b.style.position="fixed";b.style.top="56px";b.style.left="0";b.style.zIndex=String(Number("2147483646")+1);b.style.backgroundColor="rgba(255, 255, 255, 0.6)";document.body.prepend(b);_.H(window,"load",function(){b.remove()})}})();var Rx={};
(new MutationObserver(function(a){Yw(a)&&document.getElementById("google-feedback-wizard").setAttribute("translate","no")})).observe(document.body,(Rx.childList=!0,Rx));

_.oa();

}catch(e){_._DumpException(e)}
}).call(this,this.default_tr);
// Google Inc.
